services:
  app:
    build:
        context: ./docker/dev
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
    container_name: ${APP_NAME}-app
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    ports:
        - '${APP_PORT:-80}:80'
        - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
        WWWUSER: '${WWWUSER}'
        XDEBUG_MODE: '${XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
        - '.:/var/www/html'
    networks:
        - app
    depends_on:
        - mariadb
        - redis

  mariadb:
    image: 'mariadb:latest'
    container_name: ${APP_NAME}-db
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: "%"
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
        - 'app-mariadb:/var/lib/mysql'
        - './docker/dev/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
        - app
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
        retries: 3
        timeout: 5s

  redis:
    image: 'redis:alpine'
    container_name: ${APP_NAME}-redis
    ports:
        - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
        - 'app-redis:/data'
    networks:
        - app
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s
networks:
    app:
        driver: bridge
volumes:
    app-mariadb:
        driver: local
    app-redis:
        driver: local